//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celebratexp.Localize {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locares {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locares() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Celebratexp.Localize.Locares", typeof(Locares).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add day.
        /// </summary>
        internal static string AddDay {
            get {
                return ResourceManager.GetString("AddDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day name.
        /// </summary>
        internal static string DayName {
            get {
                return ResourceManager.GetString("DayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit day.
        /// </summary>
        internal static string EditDay {
            get {
                return ResourceManager.GetString("EditDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сelebration.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string PsDayTitle {
            get {
                return ResourceManager.GetString("PsDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string PsHourTitle {
            get {
                return ResourceManager.GetString("PsHourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years on Jupiter.
        /// </summary>
        internal static string PsJupiterTitle {
            get {
                return ResourceManager.GetString("PsJupiterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years on Mars.
        /// </summary>
        internal static string PsMarsTitle {
            get {
                return ResourceManager.GetString("PsMarsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string PsMinuteTitle {
            get {
                return ResourceManager.GetString("PsMinuteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string PsMonthTitle {
            get {
                return ResourceManager.GetString("PsMonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking to the Moon.
        /// </summary>
        internal static string PsMoonTitle {
            get {
                return ResourceManager.GetString("PsMoonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years on Saturn.
        /// </summary>
        internal static string PsSaturnTitle {
            get {
                return ResourceManager.GetString("PsSaturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string PsSecondTitle {
            get {
                return ResourceManager.GetString("PsSecondTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years on Venus.
        /// </summary>
        internal static string PsVenusTitle {
            get {
                return ResourceManager.GetString("PsVenusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        internal static string PsWeekTitle {
            get {
                return ResourceManager.GetString("PsWeekTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string PsYearTitle {
            get {
                return ResourceManager.GetString("PsYearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
    }
}
